### ISSUE TITLE
checkout with discount coupon 

### ISSUE THREAD

**Issue by mazenalaghbari** [PhazeRoOman/thawani-for-woocommerce#51]
![WhatsApp Image 2021-07-25 at 12 06 13 AM](https://user-images.githubusercontent.com/10177467/126888413-a8bd81f7-6bd1-4416-b293-1000a4dc5188.jpeg)
* checkout with discount coupon *

I notice that during the process of checkout,  it is not processing the payment and causing stopping because of coupon usage without it no issue in completing the process. It needs to be fixed

**Comment by w7shdev** [comment]
Thank you  @mazenalaghbari 

Discussion is opened here #50 , 

please can you provide a way to replicate the  coupon so we can start and investigate this issue on our end.

**Comment by mazenalaghbari** [comment]
it seems that the coupon sent with a minus value it could the reason for causing the error.

**Comment by w7shdev** [comment]
@mazenalaghbari  please see the recorded video ( BTW sorry for the dropping rate in the frames) 
https://github.com/PhazeRoOman/thawani-for-woocommerce/discussions/50#discussioncomment-1049068

And in order to replicate the issue we need to make the same setup and tackle the bug. 

> it seems that the coupon sent with a minus value it could the reason for causing the error.

with quick setup for the coupon my my end it seems it's working fine

**Comment by mazenalaghbari** [comment]
I reviewed the setting, the issue was because of the shipping setting.
