### ISSUE TITLE
Invalid session due to incorrect API marks the order as complete

### ISSUE THREAD

**Issue by PupaClic** [PhazeRoOman/thawani-for-woocommerce#83]
**Describe the bug**
When an order is placed using thawani and there is an issue with the API credentials. The order is being marked as processing instead of on hold. 

**To Reproduce**
Placing an order with an invalid API credential

**Expected behavior**
Order should be kept on hold and the thawarni session log should display payment error

**Comment by w7shdev** [comment]
hey @PupaClic .. 
I'll keep [WooCommerce manage order page ](https://woocommerce.com/document/managing-orders/)as a reference for why we are using failed status and pending status when the payment is created! 

On-hold is used for offline payment ( most of the e-commerce system use this status when the order is created). 


**When the order is being created** 

The  default status will be pending and not processing.

**if the credentials are incorrect**  then the payment status will be failed! and the reason is the way Thawani Pay integration works.

**Comment by w7shdev** [comment]
Hey @PupaClic is your question is answered ?
