### ISSUE TITLE
Error processing checkout. Please try again.

### ISSUE THREAD

**Issue by Knight-326** [PhazeRoOman/thawani-for-woocommerce#94]
Hey team,

Trying to setup Thawani payment for a WordPress store, followed all the steps provided here

https://github.com/PhazeRoOman/thawani-for-woocommerce

but still getting this error. 

the store location is OMAN, the currency is also Omani riyal.
if you guys can help.

thanks

**Comment by mariamalbalushi** [comment]
Thank you for reaching out to us @Knight-326
Can you provide the error showing

**Comment by Knight-326** [comment]
Thanks @mariamalbalushi for replying,

THIS ERROR.
![12121](https://user-images.githubusercontent.com/122797393/213903665-dd12c7a1-4761-4dec-9728-7e95c053d533.PNG)

**Comment by mariamalbalushi** [comment]
@Knight-326  Please make sure that you are using the correct keys (Secret key and Publishable Key)

**Comment by Knight-326** [comment]
@mariamalbalushi do u have the UAT keys?

for testing perpose?

**Comment by mariamalbalushi** [comment]
@Knight-326  These are the keys 

Secret Key: rRQ26GcsZzoEhbrP2HZvLYDbn9C9et
Publishable Key: HGvTMLDssJghr9tlN9gr4DVYt0qyBy

You can find  the keys [here!](https://docs.thawani.om/docs/thawani-ecommerce-api/5534c91789a48-thawani-e-commerce-api) and the test cards [here!](https://docs.thawani.om/docs/thawani-ecommerce-api/7c0f75e1668d7-thawani-test-card)

**Comment by Knight-326** [comment]
@mariamalbalushi let me check

**Comment by yaroub999** [comment]
hi
I have the same problem
Error processing checkout. Please try again.

**Comment by w7shdev** [comment]
Hello @Knight-326 and @yaroub999 I hope the issue is sorted on your side please check this comment https://github.com/PhazeRoOman/thawani-for-woocommerce/issues/90#issuecomment-1221318338 and I hope it will clear out the steps.. 

Things to consider when using  this plugin with default configuration ( the plugin will work with default workflow of woocommerce in the checkout .. the only requirement is to set the currency to OMR ). Any customized configuration in your store will break the plugin .. for example removing the email address in the checkout or from the user registration ... 


**Please read the [documentation](https://github.com/PhazeRoOman/thawani-for-woocommerce#readme)** and follow the steps .. 
1. Make sure that the secret key and the publishable keys are in the right forms
1. Make sure that you have set the environment to development
1. Try to checkout and see if it work.. 
2. If all the setps metioned above worked for you then please read the comment here https://github.com/PhazeRoOman/thawani-for-woocommerce/issues/90#issuecomment-1221318338
